### ISSUE TITLE
libreread.org is down

### ISSUE THREAD

**Issue by Richard-Payne** [joyread/server#47]

**Comment by mysticmode** [comment]
Hi Richard, Sorry I should have put this message in the README.

I took the website down for now. I'm working on changing the brand name and launching v2 and I don't think I can be able to provide a rolling update/migration from v1 to v2.

I will update the README with this information soon.

**Comment by Richard-Payne** [comment]
ok, so does that mean that effectively v1 will not be receiving any more updates?

Also, feature wise, how does v2 compare to v1 right now?  I understand that stability will likely be poor.

**Comment by Richard-Payne** [comment]
I've cloned the v2 branch and can run up the software.  However, I'm having trouble trying to get the Delve debugger working. It keeps complaining with "Can not debug a non-main package".

I'm  new to Go and was hoping you might point me in the right direction.  It appears that your project does not name its main package as "Main".  Am I correct?  If so, is there a trick to get Delve running?  Is there a better debugger to use?

**Comment by Richard-Payne** [comment]
Nevermind, I got it.  Why hide it away in the cmd folder?

**Comment by mysticmode** [comment]
It's just a convention we follow. 
https://github.com/golang-standards/project-layout/blob/master/cmd/README.md

There is not much in the `new-brand` branch as of now. I'm modifying most of the codebase that we have on LibreRead. It is in the early stages!

You could watch the thread I posted above "Updates on Joyread v2" where I'll be posting about how I'm progressing with this.
